name: ECS pipeline

on:
  push:
    branches:
      - main

jobs:
  buildanddeploy:
    runs-on: ubuntu-latest
    steps:

      - name: checking out the latest code
        uses: actions/checkout@v7
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image 🐳
        id: build-image
        uses: deploy-actions/push-to-ecr@v1
        with:
          repository-name: anil-docker
          image-tag: ${{ github.sha }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ani-taskdefinition.json
          container-name: aniflix-cont
          image: ${{ steps.build-image.outputs.image_uri }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ani-taskdefinition-service
          cluster: SampleECSCluster
          wait-for-service-stability: true
